# Generated by Django 5.2.5 on 2025-10-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_site_police'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id_famille', models.AutoField(primary_key=True, serialize=False)),
                ('nom_famille', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=200)),
                ('prix_produit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description_produit', models.TextField()),
                ('is_produit_du_moment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_produit_du_moment', models.BooleanField(default=False)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_produit', to='core.image')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_produit', to='products.produit')),
            ],
            options={
                'unique_together': {('image', 'produit')},
            },
        ),
    ]
