# Generated by Django 4.2.24 on 2025-10-01 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id_famille', models.AutoField(primary_key=True, serialize=False)),
                ('nom_famille', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('type_produit', models.CharField(max_length=200)),
                ('prix_produit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_produit', models.TextField()),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='products.famille')),
            ],
        ),
    ]
