# Generated by Django 5.2.5 on 2025-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='type_produit',
            new_name='nom_produit',
        ),
        migrations.AddField(
            model_name='produit',
            name='is_produit_du_moment',
            field=models.BooleanField(default=False),
        ),
    ]
