# Generated by Django 5.2.5 on 2025-10-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0002_rename_type_produit_produit_nom_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='famille',
        ),
        migrations.CreateModel(
            name='Image_Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_produit', to='core.image')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_produit', to='products.produit')),
            ],
            options={
                'unique_together': {('image', 'produit')},
            },
        ),
    ]
