# Generated by Django 5.2.5 on 2025-10-20 09:39

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Propos',
            fields=[
                ('id_ap', models.AutoField(primary_key=True, serialize=False)),
                ('ordre_ap', models.IntegerField()),
                ('titre_ap', models.CharField(max_length=1000)),
                ('description_ap', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('background', colorfield.fields.ColorField(default='#F6F2E8', image_field=None, max_length=25, samples=None)),
                ('foreground', colorfield.fields.ColorField(default='#B8A67E', image_field=None, max_length=25, samples=None)),
                ('police', models.CharField(default='Liberation Sans', max_length=200)),
                ('bandeau_hauteur', models.IntegerField(default=140)),
                ('bandeau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bandeau_site', to='core.image')),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_site', to='core.image')),
            ],
        ),
        migrations.CreateModel(
            name='Image_AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_image', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('right', 'Droite'), ('center', 'Centre'), ('left', 'Gauche')])),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.image')),
                ('page_ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_ap', to='core.a_propos')),
            ],
            options={
                'unique_together': {('images', 'page_ap')},
            },
        ),
    ]
