# Generated by Django 5.2.6 on 2025-10-01 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A_Propos',
            fields=[
                ('id_ap', models.AutoField(primary_key=True, serialize=False)),
                ('titre_ap', models.CharField(max_length=1000)),
                ('description_ap', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images')),
                ('page_ap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_ap', to='core.a_propos')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('couleur', models.CharField(max_length=7)),
                ('police', models.CharField(max_length=200)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_site', to='core.image')),
            ],
        ),
    ]
