# Generated by Django 5.2.5 on 2025-10-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='police',
            field=models.CharField(default='Alata', max_length=200),
        ),
    ]
