# Generated by Django 5.2.5 on 2025-10-14 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0002_rename_type_produit_produit_nom_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_produit', to='products.produit'),
        ),
    ]
