# Generated by Django 5.2.6 on 2025-10-14 13:03

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='page_ap',
        ),
        migrations.AlterField(
            model_name='site',
            name='couleur',
            field=colorfield.fields.ColorField(default='#B8A67E', image_field=None, max_length=25, samples=None),
        ),
        migrations.CreateModel(
            name='Image_AP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.image')),
                ('page_ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_ap', to='core.a_propos')),
            ],
            options={
                'unique_together': {('images', 'page_ap')},
            },
        ),
    ]
