# Generated by Django 5.2.5 on 2025-10-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_image_page_ap_alter_site_couleur_image_ap'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_propos',
            name='ordre_ap',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
