# Generated by Django 5.2.5 on 2025-10-15 12:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_a_propos_ordre_ap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='couleur',
            new_name='foreground',
        ),
        migrations.AddField(
            model_name='site',
            name='background',
            field=colorfield.fields.ColorField(default='#F6F2E8', image_field=None, max_length=25, samples=None),
        ),
    ]
