# Generated by Django 5.2.5 on 2025-10-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_couleur_site_foreground_site_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bandeau',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bandeau_site', to='core.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_site', to='core.image'),
        ),
    ]
