# Generated by Django 5.2.5 on 2025-10-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_produit'),
        ('core', '0004_rename_couleur_site_foreground_site_background'),
    ]

    operations = [
    ]
