# Generated by Django 5.2.5 on 2025-10-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_site_bandeau_alter_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bandeau_hauteur',
            field=models.IntegerField(default=140, max_length=1000),
            preserve_default=False,
        ),
    ]
