# Generated by Django 5.2.5 on 2025-10-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_bandeau_hauteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='bandeau_hauteur',
            field=models.IntegerField(default=140, max_length=1000),
        ),
        migrations.AlterField(
            model_name='site',
            name='police',
            field=models.CharField(default='Liberation Sans', max_length=200),
        ),
    ]
