# Generated by Django 5.2.6 on 2025-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.AutoField(primary_key=True, serialize=False)),
                ('pseudonyme', models.CharField(max_length=100)),
                ('valeur', models.IntegerField(choices=[('1 étoile', 1), ('2 étoiles', 2), ('3 étoiles', 3), ('4 étoiles', 4), ('5 étoiles', 5)])),
                ('message', models.CharField()),
            ],
        ),
    ]
