name: Pylint

on: [push]

jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: rapport test2
        path: coverage_html_report/
    - name: Analysing the code with pylint
      run: |
        flake8 $(git ls-files '*.py')
  
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: installation des dépendances
      run: pip install -r requirements.txt
    - name: mise en place des tables
      run: |
        cd ./sfabc
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Lancer les tests
      run: |
        cd ./sfabc
        python3 manage.py test
    - name: coverage
      run: |
        cd ./sfabc
        coverage run --source='apps' manage.py test ./apps/core/tests ./apps/products/tests ./apps/reviews/tests
        coverage report
